import {
  v1,
  v2,
  v3,
  v4,
  v5,
  v6,
  v7,
  v8,
  v9,
  v10,
  v11,
  v12,
  v13,
  v14,
  v15,
  v16,
  v17,
  v18,
  v19,
  v20,
  v21,
  v22,
  v23,
  v24,
  v25,
  v26,
} from "../../Assets/icons";
import {
  p1,
  p2,
  p3,
  p4,
  p5,
  p6,
  p7,
  p8,
  p9,
  p10,
  p11,
  p12,
  p13,
  p14,
  p15,
  p16,
  p17,
  p18,
  p19,
  p20,
  p21,
  p22,
  p23,
  p24,
  p25,
  p26,
} from "../../Assets/icons";
import {
  o1,
  o2,
  o3,
  o4,
  o5,
  o6,
  o7,
  o8,
  o9,
  o10,
  o11,
  o12,
  o13,
  o14,
  o15,
  o16,
  o17,
  o18,
  o19,
  o20,
  o21,
} from "../../Assets/icons";
import {
  m1,
  m2,
  m3,
  m4,
  m5,
  m6,
  m7,
  m8,
  m9,
  m10,
  m11,
  m12,
} from "../../Assets/icons";
import {
  od1,
  od2,
  od3,
  od4,
  od5,
  od6,
  od7,
  od8,
  od9,
  od10,
} from "../../Assets/icons";
import {
  a1,
  a2,
  a3,
  a4,
  a5,
  a6,
  a7,
  a8,
  a9,
  a10,
  a11,
  a12,
  a13,
  a14,
} from "../../Assets/icons";
import {
  b1,
  b2,
  b3,
  b4,
  b5,
  b6,
  b7,
  b8,
  b9,
  b10,
  b11,
  b12,
} from "../../Assets/icons";
import {
  g1,
  g2,
  g3,
  g4,
  g5,
  g6,
  g7,
  g8,
  g9,
  g10,
  g11,
  g12,
  g13,
  g14,
  g15,
  g16,
  g17,
  g18,
  g19,
} from "../../Assets/icons";
import {
  j1,
  j2,
  j3,
  j4,
  j5,
  j6,
  j7,
  j8,
  j9,
  j10,
  j11,
  j12,
  j13,
  j14,
  j15,
} from "../../Assets/icons";
import {
  bu1,
  bu2,
  bu3,
  bu4,
  bu5,
  bu6,
  bu7,
  bu8,
  bu9,
  bu10,
  bu11,
  bu12,
  bu13,
  bu14,
  bu15,
  bu16,
  bu17,
} from "../../Assets/icons";
import {
  st1,
  st2,
  st3,
  st4,
  st5,
  st6,
  st7,
  st8,
  st9,
  st10,
  st11,
  st12,
  st13,
} from "../../Assets/icons";
import {
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
  s16,
  s17,
  s18,
  s19,
  s20,
  s21,
  s22,
  s23,
} from "../../Assets/icons";
import {
  sh1,
  sh2,
  sh3,
  sh4,
  sh5,
  sh6,
  sh7,
  sh8,
  sh9,
} from "../../Assets/icons";
import {
  f1,
  f2,
  f3,
  f4,
  f5,
  f6,
  f7,
  f8,
  f9,
  f10,
  f11,
  f12,
  f13,
  f14,
  f15,
} from "../../Assets/icons";
import {
  c1,
  c2,
  c3,
  c4,
  c5,
  c6,
  c7,
  c8,
  c9,
  c10,
  c11,
  c12,
  c13,
  c14,
  c15,
  c16,
  c17,
  c18,
  c19,
} from "../../Assets/icons";
import {
  t1,
  t2,
  t3,
  t4,
  t5,
  t6,
  t7,
  t8,
  t9,
  t10,
  t11,
  t12,
  t13,
  t14,
  t15,
  t16,
  t17,
  t18,
  t19,
  t20,
  t21,
  t22,
} from "../../Assets/icons";
import {
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  h7,
  h8,
  h9,
  h10,
  h11,
  h12,
  h13,
  h14,
  h15,
  h16,
  h17,
  h18,
  h19,
  h20,
  h21,
  h22,
} from "../../Assets/icons";
import {
  x1,
  x2,
  x3,
  x4,
  x5,
  x6,
  x7,
  x8,
  x9,
  x10,
  x11,
  x12,
  x13,
  x14,
  x15,
  x16,
  x17,
  x18,
  x19,
  x20,
  x21,
  x22,
  x23,
  x24,
  x25,
  x26,
  x27,
  x28,
  x29,
  x30,
  x31,
  x32,
  x33,
  x34,
  x35,
  x36,
  x37,
} from "../../Assets/icons";
function createData(name, Collection, Weapon, Source) {
  return { name, Collection, Weapon, Source };
}

const rows = [
  createData(v1, "Aristocrat", "Vandal", "Store"),
  createData(v2, "Avalanche", "Vandal", "Store"),
  createData(v3, "Cavalier", "Vandal", "Episode 02: Act 2 Battle Pass"),
  createData(v4, "Depths", "Vandal", "Episode 02: Act 3 Battle Pass"),
  createData(v5, "DOT EXE", "Vandal", "Episode 01: Act 1 Battle Pass"),
  createData(v6, "Ego", "Vandal", "Store"),
  createData(v7, "Elderflame", "Vandal", "Store"),
  createData(v8, "Forsaken", "Vandal", "Store"),
  createData(v9, "Glitchpop", "Vandal", "Store"),
  createData(v10, "Hivemind", "Vandal", "Episode 01: Act 2 Battle Pass"),
  createData(v11, "Horizon", "Vandal", "Store"),
  createData(v12, "K/TAC", "Vandal", "Episode 03: Act 1 Battle Pass"),
  createData(v13, "Luxe", "Vandal", "Store"),
  createData(v14, "Origin", "Vandal", "Store"),
  createData(v15, "Prime", "Vandal", "Store"),
  createData(v16, "Prism II", "Vandal", "Store"),
  createData(v17, "Reaver", "Vandal", "Store"),
  createData(v18, "Ruin", "Vandal", "Episode 01: Act 3 Battle Pass"),
  createData(v19, "Sakura", "Vandal", "Store"),
  createData(v20, "Sensation", "Vandal", "Store"),
  createData(v21, "Sentinels of Light", "Vandal", "Store"),
  createData(v22, "Silvanus", "Vandal", "Store"),
  createData(v23, "Tethered Realms", "Vandal", "Store"),
  createData(v24, "Wasteland", "Vandal", "Store"),
  createData(v25, "Winterwunderland", "Vandal", "Store"),
  createData(v26, "Nitro", "Vandal", "Episode 03: Act 2 Battle Pass"),

  createData(p1, "Avalanche", "Phantom", "Store"),
  createData(p2, "BlastX", "Phantom", "Store"),
  createData(p3, "Celestial", "Phantom", "Store"),
  createData(p4, "Galleria", "Phantom", "Store"),
  createData(p5, "Glitchpop", "Phantom", "Store"),
  createData(p6, "Infinity", "Phantom", "Episode 02: Act 1 Battle Pass"),
  createData(p7, "Ion", "Phantom", "Store"),
  createData(p8, "Kingdom", "Phantom", "Episode 01: Act 1 Battle Pass"),
  createData(p9, "Lightwave", "Phantom", "Episode 02: Act 3 Battle Pass"),
  createData(p10, "Minima", "Phantom", "Store"),
  createData(p11, "Nebula", "Phantom", "Store"),
  createData(p12, "Oni", "Phantom", "Store"),
  createData(p13, "Prime//2.0", "Phantom", "Store"),
  createData(p14, "Prism", "Phantom", "Store"),
  createData(p15, "Recon", "Phantom", "Store"),
  createData(p16, "Ruination", "Phantom", "Store"),
  createData(p17, "Rush", "Phantom", "Store"),
  createData(p18, "Serenity", "Phantom", "Episode 01: Act 3 Battle Pass"),
  createData(p19, "Silvanus", "Phantom", "Store"),
  createData(p20, "Singularity", "Phantom", "Store"),
  createData(p21, "Smite", "Phantom", "Store"),
  createData(p22, "Spline", "Phantom", "Store"),
  createData(p23, "VALORANT Go! Vol. 1", "Phantom", "Store"),
  createData(p24, "Winterwunderland", "Phantom", "Store"),
  createData(p25, "Artisan", "Phantom", "Episode 03: Act 2 Battle Pass"),
  createData(p26, "Spectrum", "Phantom", "Store"),

  createData(m1, "Avalanche", "Marshal", "Store"),
  createData(m2, "Couture", "Marshal", "Episode 01: Act 1 Battle Pass"),
  createData(m3, "Galleria", "Marshal", "Store"),
  createData(m4, "Magepunk", "Marshal", "Store"),
  createData(m5, "Monarch", "Marshal", "Episode 03: Act 1 Battle Pass"),
  createData(m6, "Polyfrog", "Marshal", "Episode 02: Act 2 Battle Pass"),
  createData(m7, "Ruin", "Marshal", "Episode 01: Act 3 Battle Pass"),
  createData(m8, "Songsteel", "Marshal", "Episode 02: Act 3 Battle Pass"),
  createData(m9, "Sovereign", "Marshal", "Store"),
  createData(m10, "Wasteland", "Marshal", "Store"),
  createData(m11, "Winterwunderland", "Marshal", "Store"),
  createData(m12, "Artisan", "Marshal", "Episode 03: Act 2 Battle Pass"),

  createData(o1, "Aerosol", "Operator", "Episode 02: Act 1 Battle Pass"),
  createData(o2, "Cavalier", "Operator", "Episode 02: Act 2 Battle Pass"),
  createData(o3, "Convex", "Operator", "Store"),
  createData(o4, "Elderflame", "Operator", "Store"),
  createData(o5, "Forsaken", "Operator", "Store"),
  createData(o6, "Glitchpop", "Operator", "Store "),
  createData(o7, "Gravitational Uranium Neuroblaster", "Operator", "Store"),
  createData(o8, "Infantry", "Operator", "Store"),
  createData(o9, "Ion", "Operator", "Store"),
  createData(o10, "K/TAC", "Operator", "Episode 03: Act 1 Battle Pass"),
  createData(o11, "Luxe", "Operator", "Store"),
  createData(o12, "Minima", "Operator", "Store"),
  createData(o13, "Origin", "Operator", "Store"),
  createData(o14, "Prism", "Operator", "Store"),
  createData(o15, "Reaver", "Operator", "Store"),
  createData(o16, "Red Alert", "Operator", "Episode 01: Act 2 Battle Pass"),
  createData(o17, "Sentinels of Light", "Operator", "Store"),
  createData(o18, "Silvanus", "Operator", "Store"),
  createData(o19, "Spline", "Operator", "Store"),
  createData(o20, "Tethered Realms", "Operator", "Store"),
  createData(o21, "Nitro", "Operator", "Episode 03: Act 2 Battle Pass"),

  createData(od1, "Aerosol", "Odin", "Episode 02: Act 1 Battle Pass"),
  createData(od2, "BlastX", "Odin", "Store"),
  createData(od3, "DOT EXE", "Odin", "Episode 01: Act 1 Battle Pass"),
  createData(od4, "Glitchpop", "Odin", "Store"),
  createData(od5, "Lightwave", "Odin", "Episode 02: Act 3 Battle Pass"),
  createData(od6, "Prime//2.0", "Odin", "Store"),
  createData(od7, "Prism III", "Odin", "Episode 02: Act 2 Battle Pass"),
  createData(od8, "Sensation", "Odin", "Store"),
  createData(od9, "Smite", "Odin", "Store"),
  createData(od10, "Nitro", "Odin", "Episode 03: Act 2 Battle Pass"),

  createData(a1, "Aristocrat", "Ares", "Store"),
  createData(a2, "Celestial", "Ares", "Store"),
  createData(a3, "Hivemind", "Ares", "Episode 01: Act 2 Battle Pass"),
  createData(a4, "Infantry", "Ares", "Store"),
  createData(a5, "Jigsaw", "Ares", "Episode 03: Act 1 Battle Pass"),
  createData(a6, "Minima", "Ares", "Store"),
  createData(a7, "Nebula", "Ares", "Store"),
  createData(a8, "Outpost", "Ares", "Episode 02: Act 1 Battle Pass"),
  createData(a9, "Polyfrog", "Ares", "Episode 02: Act 2 Battle Pass"),
  createData(a10, "Prism", "Ares", "Store"),
  createData(a11, "Rush", "Ares", "Store"),
  createData(a12, "Sakura", "Ares", "Store"),
  createData(a13, "Sentinels of Light", "Ares", "Store"),
  createData(a14, "Singularity", "Ares", "Store"),

  createData(b1, "Aristocrat", "Bulldog", "Store"),
  createData(b2, "Convex", "Bulldog", "Store"),
  createData(b3, "Couture", "Bulldog", "Episode 01: Act 1 Battle Pass"),
  createData(b4, "Depths", "Bulldog", "Episode 02: Act 3 Battle Pass"),
  createData(b5, "Glitchpop", "Bulldog", "Store"),
  createData(b6, "Horizon", "Bulldog", "Store"),
  createData(b7, "Infinity", "Bulldog", "Episode 02: Act 1 Battle Pass"),
  createData(b8, "K/TAC", "Bulldog", "Episode 03: Act 1 Battle Pass"),
  createData(b9, "Polyfox", "Bulldog", "Episode 01: Act 2 Battle Pass"),
  createData(b10, "Rush", "Bulldog", "Store"),
  createData(b11, "Varnish", "Bulldog", "Episode 03: Act 2 Battle Pass"),
  createData(b12, "Spectrum", "Bulldog", "Store"),

  createData(g1, "Ego", "Guardian", "Store"),
  createData(g2, "Galleria", "Guardian", "Store"),
  createData(g3, "Infantry", "Guardian", "Store"),
  createData(g4, "Infinity", "Guardian", "Episode 02: Act 1 Battle Pass"),
  createData(g5, "Jigsaw", "Guardian", "Episode 03: Act 1 Battle Pass"),
  createData(g6, "Nebula", "Guardian", "Store"),
  createData(g7, "Oni", "Guardian", "Store"),
  createData(g8, "Polyfox", "Guardian", "Episode 01: Act 2 Battle Pass"),
  createData(g9, "Prime", "Guardian", "Store"),
  createData(g10, "Reaver", "Guardian", "Store"),
  createData(g11, "Recon", "Guardian", "Store"),
  createData(g12, "Ruin", "Guardian", "Episode 01: Act 3 Battle Pass"),
  createData(g13, "Ruination", "Guardian", "Store"),
  createData(g14, "Songsteel", "Guardian", "Episode 02: Act 3 Battle Pass"),
  createData(g15, "Sovereign", "Guardian", "Store"),
  createData(g16, "Tethered Realms", "Guardian", "Store"),
  createData(g17, "VALORANT Go! Vol. 1", "Guardian", "Store"),
  createData(g18, "Nitro", "Guardian", "Episode 03: Act 2 Battle Pass"),
  createData(g19, "Spectrum", "Guardian", "Store"),

  createData(j1, "Celestial", "Judge", "Store"),
  createData(j2, "Convex", "Judge", "Store"),
  createData(j3, "DOT EXE", "Judge", "Episode 01: Act 1 Battle Pass"),
  createData(j4, "Elderflame", "Judge", "Store"),
  createData(j5, "Glitchpop", "Judge", "Store"),
  createData(j6, "Jigsaw", "Judge", "Episode 03: Act 1 Battle Pass"),
  createData(j7, "Luxe", "Judge", "Store"),
  createData(j8, "Outpost", "Judge", "Episode 02: Act 1 Battle Pass"),
  createData(j9, "Polyfox", "Judge", "Episode 01: Act 2 Battle Pass"),
  createData(j10, "Prism III", "Judge", "Episode 02: Act 2 Battle Pass"),
  createData(j11, "Rush", "Judge", "Store"),
  createData(j12, "Sensation", "Judge", "Store"),
  createData(j13, "Serenity", "Judge", "Episode 01: Act 3 Battle Pass"),
  createData(j14, "Smite", "Judge", "Store"),
  createData(j15, "Varnish", "Judge", "StoreEpisode 03: Act 2 Battle Pass"),

  createData(bu1, "Aerosol", "Bucky", "Episode 02: Act 1 Battle Pass"),
  createData(bu2, "Cavalier", "Bucky", "Episode 02: Act 2 Battle Pass"),
  createData(bu3, "Galleria", "Bucky", "Store"),
  createData(bu4, "Gravitational Uranium Neuroblaster", "Bucky", "Store"),
  createData(bu5, "Horizon", "Bucky", "Store"),
  createData(bu6, "Ion", "Bucky", "Store"),
  createData(bu7, "Kingdom", "Bucky", "Episode 01: Act 1 Battle Pass"),
  createData(bu8, "Lightwave", "Bucky", "Episode 02: Act 3 Battle Pass"),
  createData(bu9, "Magepunk", "Bucky", "Store"),
  createData(bu10, "Monarch", "Bucky", "Episode 03: Act 1 Battle Pass"),
  createData(bu11, "Oni", "Bucky", "Store"),
  createData(bu12, "Origin", "Bucky", "Store"),
  createData(bu13, "Prime//2.0", "Bucky", "Store"),
  createData(bu14, "Prism II", "Bucky", "Store"),
  createData(bu15, "Red Alert", "Bucky", "Episode 01: Act 2 Battle Pass"),
  createData(bu16, "Surge", "Bucky", "Episode 01: Act 3 Battle Pass"),
  createData(bu17, "Artisan", "Bucky", "Episode 03: Act 2 Battle Pass"),

  createData(st1, "Aristocrat", "Stinger", "Store"),
  createData(st2, "Cavalier", "Stinger", "Episode 02: Act 2 Battle Pass"),
  createData(st3, "Couture", "Stinger", "Episode 01: Act 1 Battle Pass"),
  createData(st4, "Depths", "Stinger", "Episode 02: Act 3 Battle Pass"),
  createData(st5, "Ego", "Stinger", "Store"),
  createData(st6, "Prism II", "Stinger", "Store"),
  createData(st7, "Red Alert", "Stinger", "Episode 01: Act 2 Battle Pass"),
  createData(st8, "Sakura", "Stinger", "Store"),
  createData(st9, "Sensation", "Stinger", "Store"),
  createData(st10, "Silvanus", "Stinger", "Store"),
  createData(st11, "Sovereign", "Stinger", "Store"),
  createData(st12, "Surge", "Stinger", "Episode 01: Act 3 Battle Pass"),
  createData(st13, "Varnish", "Stinger", "Episode 03: Act 2 Battle Pass"),

  createData(s1, "Avalanche", "Spectre", "Store"),
  createData(s2, "BlastX", "Spectre", "Store"),
  createData(s3, "Convex", "Spectre", "Store"),
  createData(s4, "Forsaken", "Spectre", "Store"),
  createData(s5, "Gravitational Uranium Neuroblaster", "Spectre", "Store"),
  createData(s6, "Hivemind", "Spectre", "Episode 01: Act 2 Battle Pass"),
  createData(s7, "Horizon", "Spectre", "Store"),
  createData(s8, "Infantry", "Spectre", "Store"),
  createData(s9, "Infinity", "Spectre", "Episode 02: Act 1 Battle Pass"),
  createData(s10, "Kingdom", "Spectre", "Episode 01: Act 1 Battle Pass"),
  createData(s11, "Luxe", "Spectre", "Store"),
  createData(s12, "Magepunk", "Spectre", "Store"),
  createData(s13, "Minima", "Spectre", "Store"),
  createData(s14, "Polyfrog", "Spectre", "Episode 02: Act 2 Battle Pass"),
  createData(s15, "Prime", "Spectre", "Store"),
  createData(s16, "Prism", "Spectre", "Store"),
  createData(s17, "Recon", "Spectre", "Store"),
  createData(s18, "Ruination", "Spectre", "Store"),
  createData(s19, "Serenity", "Spectre", "Episode 01: Act 3 Battle Pass"),
  createData(s20, "Singularity", "Spectre", "Store"),
  createData(s21, "Spline", "Spectre", "Store"),
  createData(s22, "VALORANT Go! Vol. 1", "Spectre", "Store"),
  createData(s23, "Wasteland", "Spectre", "Store"),

  createData(sh1, "Aerosol", "Shorty", "Episode 02: Act 1 Battle Pass"),
  createData(sh2, "Hivemind", "Shorty", "Episode 01: Act 2 Battle Pass"),
  createData(sh3, "Monarch", "Shorty", "Episode 03: Act 1 Battle Pass"),
  createData(sh4, "Oni", "Shorty", "Store"),
  createData(sh5, "Prism II", "Shorty", "Store"),
  createData(sh6, "Ruin", "Shorty", "Episode 01: Act 3 Battle Pass"),
  createData(sh7, "Snakebite", "Shorty", "Contract: Viper"),
  createData(sh8, "Wasteland", "Shorty", "Store"),
  createData(sh9, "Wunderkind", "Shorty", "Contract: Killjoy"),

  createData(f1, "BlastX", "Frenzy", "Store"),
  createData(f2, "Celestial", "Frenzy", "Store"),
  createData(f3, "Couture", "Frenzy", "Episode 01: Act 1 Battle Pass"),
  createData(f4, "Elderflame", "Frenzy", "Store"),
  createData(f5, "Glitchpop", "Frenzy", "Store"),
  createData(f6, "Horizon", "Frenzy", "Store"),
  createData(f7, "Lightwave", "Frenzy", "Episode 02: Act 3 Battle Pass"),
  createData(f8, "Monarch", "Frenzy", "Episode 03: Act 1 Battle Pass"),
  createData(f9, "Origin", "Frenzy", "Store"),
  createData(f10, "Prime//2.0", "Frenzy", "Store"),
  createData(f11, "Ragnarocker", "Frenzy", "Contract: Breach"),
  createData(f12, "Rush", "Frenzy", "Store"),
  createData(f13, "Sensation", "Frenzy", "Store"),
  createData(f14, "Spitfire", "Frenzy", "Contract: Phoenix"),
  createData(f15, "Swooping", "Frenzy", "Contract: Skye"),

  createData(c1, "Avalanche", "Classic", "Store"),
  createData(c2, "Final Chamber", "Classic", "Contract: Sage"),
  createData(c3, "FIRE/arm", "Classic", "Contract: KAYO"),
  createData(c4, "Forsaken", "Classic", "Store"),
  createData(c5, "Galleria", "Classic", "Store"),
  createData(c6, "Glitchpop", "Classic", "Store"),
  createData(c7, "Gravitational Uranium Neuroblaster", "Classic", "Store"),
  createData(c8, "Infinity", "Classic", "Episode 02: Act 1 Battle Pass"),
  createData(c9, "Kingdom", "Classic", "Episode 01: Act 1 Battle Pass"),
  createData(c10, "Pistolinha", "Classic", "Contract: Raze"),
  createData(c11, "Prime", "Classic", "Store"),
  createData(c12, "Prism III", "Classic", "Episode 02: Act 2 Battle Pass"),
  createData(c13, "Red Alert", "Classic", "Episode 01: Act 2 Battle Pass"),
  createData(c14, "Sakura", "Classic", "Store"),
  createData(c15, "Smite", "Classic", "Store"),
  createData(c16, "Songsteel", "Classic", "Episode 02: Act 3 Battle Pass"),
  createData(c17, "Spline", "Classic", "Store"),
  createData(c18, "Surge", "Classic", "Episode 01: Act 3 Battle Pass"),
  createData(c19, "Spectrum", "Classic", "Store"),

  createData(t1, "Cavalier", "Ghost", "Episode 02: Act 2 Battle Pass"),
  createData(t2, "Depths", "Ghost", "Episode 02: Act 3 Battle Pass"),
  createData(t3, "DOT EXE", "Ghost", "Episode 01: Act 1 Battle Pass"),
  createData(t4, "Eclipse", "Ghost", "Contract: Astra"),
  createData(t5, "Ego", "Ghost", "Store"),
  createData(t6, "Hush", "Ghost", "Contract: Cypher"),
  createData(t7, "Infantry", "Ghost", "Store"),
  createData(t8, "Jigsaw", "Ghost", "Episode 03: Act 1 Battle Pass"),
  createData(t9, "Luxe", "Ghost", "Store"),
  createData(t10, "Magepunk", "Ghost", "Store"),
  createData(t11, "Outpost", "Ghost", "Episode 02: Act 1 Battle Pass"),
  createData(t12, "Prism", "Ghost", "Store"),
  createData(t13, "Recon", "Ghost", "Store"),
  createData(t14, "Ruination", "Ghost", "Store"),
  createData(t15, "Serenity", "Ghost", "Episode 01: Act 3 Battle Pass"),
  createData(t16, "Soul Silencer", "Ghost", "Contract: Omen"),
  createData(t17, "Sovereign", "Ghost", "Store"),
  createData(t18, "Tethered Realms", "Ghost", "Store"),
  createData(t19, "VALORANT Go! Vol. 1", "Ghost", "Store"),
  createData(t20, "Vendetta", "Ghost", "Contract: Reyna"),
  createData(t21, "Winterwunderland", "Ghost", "Store"),
  createData(t22, "Artisan", "Ghost", "Episode 03: Act 2 Battle Pass"),

  createData(h1, "Aristocrat", "Sheriff", "Store"),
  createData(h2, "Convex", "Sheriff", "Store"),
  createData(h3, "Death Wish", "Sheriff", "Store"),
  createData(h4, "Game Over", "Sheriff", "Store"),
  createData(h5, "Ion", "Sheriff", "Store"),
  createData(h6, "K/TAC", "Sheriff", "Store"),
  createData(h7, "Lightwave", "Sheriff", "Store"),
  createData(h8, "Minima", "Sheriff", "Store"),
  createData(h9, "Nebula", "Sheriff", "Store"),
  createData(h10, "Peacekeeper", "Sheriff", "Store"),
  createData(h11, "Polyfox", "Sheriff", "Store"),
  createData(h12, "Polyfrog", "Sheriff", "Store"),
  createData(h13, "Prism II", "Sheriff", "Store"),
  createData(h14, "Protektor", "Sheriff", "Store"),
  createData(h15, "Reaver", "Sheriff", "Store"),
  createData(h16, "Sakura", "Sheriff", "Store"),
  createData(h17, "Sentinels of Light", "Sheriff", "Store"),
  createData(h18, "Silvanus", "Sheriff", "Store"),
  createData(h19, "Singularity", "Sheriff", "Store"),
  createData(h20, "Surge", "Sheriff", "Store"),
  createData(h21, "Wasteland", "Sheriff", "Store"),
  createData(h22, "Varnish", "Sheriff", "Episode 03: Act 2 Battle Pass"),

  createData(x1, "Hivemind", "Knife", "Episode 01: Act 2 Battle Pass"),
  createData(x2, "Sovereign", "Knife", "Store"),
  createData(x3, "Forsaken", "Knife", "Store"),
  createData(x4, "Sentinels of Light", "Knife", "Store"),
  createData(x5, "Tethered Realms", "Knife", "Store"),
  createData(x6, "BlastX", "Knife", "Store"),
  createData(x7, "Outpost", "Knife", "Episode 02: Act 1 Battle Pass"),
  createData(x8, "Songsteel", "Knife", "Episode 02: Act 3 Battle Pass"),
  createData(x9, "Ego", "Knife", "Store"),
  createData(x10, "Kingdom", "Knife", "Episode 01: Act 1 Battle Pass"),
  createData(x11, "Luxe", "Knife", "Store"),
  createData(x12, "Nebula", "Knife", "Store"),
  createData(x13, "Prism", "Knife", "Store"),
  createData(x14, "Reaver", "Knife", "Store"),
  createData(x15, "Singularity", "Knife", "Store"),
  createData(x16, "Smite", "Knife", "Store"),
  createData(x17, "VALORANT Go! Vol. 1", "Knife", "Store"),
  createData(x18, "Prime//2.0", "Knife", "Store"),
  createData(x19, "Celestial", "Knife", "Store"),
  createData(x20, "Ion", "Knife", "Store"),
  createData(x21, "Magepunk", "Knife", "Store"),
  createData(x22, "Elderflame", "Knife", "Store"),
  createData(x23, "Glitchpop", "Knife", "Store"),
  createData(x24, "Ruin", "Knife", "Episode 01: Act 3 Battle Pass"),
  createData(x25, "Spline", "Knife", "Store"),
  createData(x26, "Origin", "Knife", "Store"),
  createData(x27, "Oni", "Knife", "Store"),
  createData(x28, "Winterwunderland", "Knife", "Store"),
  createData(x29, "Ruination", "Knife", "Store"),
  createData(x30, "K/TAC", "Knife", "Episode 03: Act 1 Battle Pass"),
  createData(x31, "Gravitational Uranium Neuroblaster", "Knife", "Store"),
  createData(x32, "Recon", "Knife", "Store"),
  createData(x33, "Glitchpop", "Knife", "Store"),
  createData(x34, "Prime", "Knife", "Store"),
  createData(x35, "Prism III", "Knife", "Episode 02: Act 2 Battle Pass"),
  createData(x36, "Artisan", "Knife", "Episode 03: Act 2 Battle Pass"),
  createData(x37, "Spectrum", "Knife", "Store"),
];
const headCells = [
  { id: "name", numeric: false, disablePadding: true, label: "Skin" },
  {
    id: "Collection",
    numeric: false,
    disablePadding: false,
    label: "Collection",
  },
  { id: "Weapon", numeric: false, disablePadding: false, label: "Weapon" },
  { id: "Source", numeric: false, disablePadding: false, label: "Source" },
];
export { rows, headCells };
